import { resolveExercise } from "../../exercise-resolver/services/exerciseResolverService";
import type { ExerciseCatalogItem } from "../../exercise-catalog";
import type { ProgramCategory } from "../../programs/types/program.types";
import type { WorkoutTarget } from "../types/condition.types";
import type { WorkoutHistoryRecord } from "../providers/workoutHistoryProvider";
import { normalizeText } from "../../../utils/normalizeText";
export type CapacityConfidence="none"|"low"|"medium";
export interface CapacityObservation { workoutDate:Date; exerciseIdentity:{source:"catalog"|"name";value:string}; categories:ProgramCategory[]; observedSetCount?:number; observedReps?:number; observedWeight?:number; completion?:boolean; confidence:Exclude<CapacityConfidence,"none">; }
export interface CapacityProfileContext { target?:WorkoutTarget|null; maxObservations?:number; }
export interface MemberCapacityProfile { observations:CapacityObservation[]; usableObservationCount:number; matchingExerciseIdentityCount:number; observedSetCountMedian:number|null; observedSetCountRange:{min:number;max:number}|null; hasObservedSetData:boolean; hasObservedRepsData:boolean; hasObservedLoadData:boolean; hasCompletionData:boolean; confidence:CapacityConfidence; evidence:string[]; }
const cats=(r:WorkoutHistoryRecord):ProgramCategory[]=>r.categories??(r.category?[r.category]:[]); const num=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)&&v>=0?v:undefined; const valid=(d:Date)=>d instanceof Date&&!Number.isNaN(d.getTime()); const reps=(v?:string)=>v?.trim()&&/^\d+(?:\.\d+)?$/.test(v.trim())?num(Number(v)):undefined;
const observation=(r:WorkoutHistoryRecord,e:WorkoutHistoryRecord["exercises"][number],catalog:ExerciseCatalogItem[]):CapacityObservation|null=>{if(!valid(r.workoutDate))return null;const found=resolveExercise({text:e.name,catalog}).exercise,name=normalizeText(e.name);if(!found&&!name)return null;const sets=num(e.sets),rps=reps(e.reps),weight=num(e.weight);return{workoutDate:r.workoutDate,exerciseIdentity:found?{source:"catalog",value:found.id}:{source:"name",value:name},categories:cats(r),...(sets===undefined?{}:{observedSetCount:sets}),...(rps===undefined?{}:{observedReps:rps}),...(weight===undefined?{}:{observedWeight:weight}),...(r.completion===undefined?{}:{completion:r.completion}),confidence:found&&sets!==undefined?"medium":"low"};};
export const selectRecentCapacityObservations=(history:WorkoutHistoryRecord[],catalog:ExerciseCatalogItem[],context:CapacityProfileContext={}):CapacityObservation[]=>history.filter(r=>valid(r.workoutDate)&&(!context.target||cats(r).includes(context.target))).flatMap(r=>r.exercises.map(e=>observation(r,e,catalog)).filter((x):x is CapacityObservation=>Boolean(x))).sort((a,b)=>b.workoutDate.getTime()-a.workoutDate.getTime()).slice(0,Math.max(1,Math.min(5,Math.floor(context.maxObservations??5))));
export const buildMemberCapacityProfile=(history:WorkoutHistoryRecord[],catalog:ExerciseCatalogItem[],context:CapacityProfileContext={}):MemberCapacityProfile=>{const observations=selectRecentCapacityObservations(history,catalog,context),sets=observations.flatMap(x=>x.observedSetCount===undefined?[]:[x.observedSetCount]),ids=new Set(observations.map(x=>`${x.exerciseIdentity.source}:${x.exerciseIdentity.value}`)),repeat=observations.length>ids.size,sorted=[...sets].sort((a,b)=>a-b),m=Math.floor(sorted.length/2),median=sets.length<3?null:sorted.length%2?sorted[m]:(sorted[m-1]+sorted[m])/2,evidence=[observations.length&&"valid_observations",repeat&&"repeated_identity",sets.length&&"observed_sets",observations.some(x=>x.observedReps!==undefined)&&"observed_reps",observations.some(x=>x.observedWeight!==undefined)&&"observed_weight",observations.some(x=>x.completion!==undefined)&&"completion"].filter((x):x is string=>Boolean(x));return{observations,usableObservationCount:observations.length,matchingExerciseIdentityCount:ids.size,observedSetCountMedian:median,observedSetCountRange:sets.length>=3?{min:Math.min(...sets),max:Math.max(...sets)}:null,hasObservedSetData:!!sets.length,hasObservedRepsData:observations.some(x=>x.observedReps!==undefined),hasObservedLoadData:observations.some(x=>x.observedWeight!==undefined),hasCompletionData:observations.some(x=>x.completion!==undefined),confidence:observations.length>=3&&sets.length>=3&&repeat?"medium":observations.length?"low":"none",evidence};};