import type { ExerciseCatalogFormValues } from "../domain/exerciseCatalog.types";
import { normalizeAliases } from "../services/exerciseCatalogService";

const item = (
  name: string,
  englishName: string,
  aliases: string[],
  category: ExerciseCatalogFormValues["category"],
  primaryMuscle: ExerciseCatalogFormValues["primaryMuscle"],
  equipmentType: ExerciseCatalogFormValues["equipmentType"],
  movementPattern: ExerciseCatalogFormValues["movementPattern"],
): ExerciseCatalogFormValues => ({
  name,
  englishName,
  aliases: normalizeAliases(name, aliases),
  category,
  primaryMuscle,
  secondaryMuscles: [],
  equipmentType,
  movementPattern,
  difficulty: null,
  memo: "",
  isFavorite: false,
});

export const initialExerciseCatalogSeed: ExerciseCatalogFormValues[] = [
  item("벤치프레스", "Bench Press", ["bench press", "bp", "바벨 벤치"], "chest", "chest", "barbell", "push"),
  item("덤벨 벤치프레스", "Dumbbell Bench Press", ["db bench", "덤벨벤치"], "chest", "chest", "dumbbell", "push"),
  item("인클라인 벤치프레스", "Incline Bench Press", ["incline bench", "윗가슴 벤치"], "chest", "chest", "barbell", "push"),
  item("인클라인 덤벨프레스", "Incline Dumbbell Press", ["incline db press"], "chest", "chest", "dumbbell", "push"),
  item("체스트프레스", "Chest Press", ["machine chest press", "머신 체스트"], "chest", "chest", "machine", "push"),
  item("펙덱플라이", "Pec Deck Fly", ["pec deck", "팩덱", "펙덱"], "chest", "chest", "machine", "isolation"),
  item("케이블 플라이", "Cable Fly", ["cable fly", "케이블 크로스오버"], "chest", "chest", "cable", "isolation"),
  item("푸쉬업", "Push Up", ["pushup", "push-up", "팔굽혀펴기"], "chest", "chest", "bodyweight", "push"),
  item("딥스", "Dips", ["dip", "가슴 딥스"], "chest", "chest", "bodyweight", "push"),
  item("풀오버", "Pullover", ["dumbbell pullover", "덤벨 풀오버"], "chest", "lats", "dumbbell", "pull"),
  item("랫풀다운", "Lat Pulldown", ["렛풀다운", "lat pull down", "latpd"], "back", "lats", "cable", "pull"),
  item("풀업", "Pull Up", ["pullup", "턱걸이"], "back", "lats", "bodyweight", "pull"),
  item("친업", "Chin Up", ["chinup", "친 업"], "back", "lats", "bodyweight", "pull"),
  item("바벨 로우", "Barbell Row", ["bb row", "벤트오버 로우"], "back", "upper_back", "barbell", "pull"),
  item("덤벨 로우", "Dumbbell Row", ["db row", "원암 덤벨 로우"], "back", "lats", "dumbbell", "pull"),
  item("시티드 로우", "Seated Row", ["cable row", "롱풀"], "back", "upper_back", "cable", "pull"),
  item("머신 로우", "Machine Row", ["로우 머신"], "back", "upper_back", "machine", "pull"),
  item("티바 로우", "T Bar Row", ["t-bar row", "티바로우"], "back", "upper_back", "machine", "pull"),
  item("데드리프트", "Deadlift", ["dead lift", "컨벤셔널 데드"], "back", "hamstrings", "barbell", "hinge"),
  item("백 익스텐션", "Back Extension", ["hyper extension", "하이퍼익스텐션"], "back", "glutes", "bodyweight", "hinge"),
  item("숄더프레스", "Shoulder Press", ["shoulder press", "오버헤드 프레스"], "shoulder", "front_delts", "dumbbell", "push"),
  item("바벨 숄더프레스", "Barbell Shoulder Press", ["military press", "밀리터리 프레스"], "shoulder", "front_delts", "barbell", "push"),
  item("머신 숄더프레스", "Machine Shoulder Press", ["머신 어깨프레스"], "shoulder", "front_delts", "machine", "push"),
  item("사이드 레터럴 레이즈", "Side Lateral Raise", ["lateral raise", "사레레"], "shoulder", "side_delts", "dumbbell", "isolation"),
  item("프론트 레이즈", "Front Raise", ["front raise"], "shoulder", "front_delts", "dumbbell", "isolation"),
  item("리어델트 플라이", "Rear Delt Fly", ["rear delt", "후면어깨 플라이"], "shoulder", "rear_delts", "machine", "isolation"),
  item("페이스풀", "Face Pull", ["facepull", "케이블 페이스풀"], "shoulder", "rear_delts", "cable", "pull"),
  item("업라이트 로우", "Upright Row", ["upright row"], "shoulder", "side_delts", "barbell", "pull"),
  item("바벨 컬", "Barbell Curl", ["bb curl", "이두 컬"], "arm", "biceps", "barbell", "isolation"),
  item("덤벨 컬", "Dumbbell Curl", ["db curl", "암 컬"], "arm", "biceps", "dumbbell", "isolation"),
  item("해머 컬", "Hammer Curl", ["hammer curl"], "arm", "biceps", "dumbbell", "isolation"),
  item("케이블 컬", "Cable Curl", ["cable curl"], "arm", "biceps", "cable", "isolation"),
  item("프리처 컬", "Preacher Curl", ["preacher curl"], "arm", "biceps", "machine", "isolation"),
  item("트라이셉스 푸쉬다운", "Triceps Pushdown", ["push down", "케이블 푸쉬다운"], "arm", "triceps", "cable", "isolation"),
  item("라잉 트라이셉스 익스텐션", "Lying Triceps Extension", ["스컬크러셔", "skull crusher"], "arm", "triceps", "barbell", "isolation"),
  item("오버헤드 트라이셉스 익스텐션", "Overhead Triceps Extension", ["overhead extension"], "arm", "triceps", "dumbbell", "isolation"),
  item("클로즈그립 벤치프레스", "Close Grip Bench Press", ["close grip bench"], "arm", "triceps", "barbell", "push"),
  item("리스트 컬", "Wrist Curl", ["wrist curl"], "arm", "forearm", "dumbbell", "isolation"),
  item("스쿼트", "Squat", ["barbell squat", "백스쿼트"], "lower_body", "quadriceps", "barbell", "squat"),
  item("프론트 스쿼트", "Front Squat", ["front squat"], "lower_body", "quadriceps", "barbell", "squat"),
  item("레그프레스", "Leg Press", ["leg press"], "lower_body", "quadriceps", "machine", "squat"),
  item("레그 익스텐션", "Leg Extension", ["leg extension"], "lower_body", "quadriceps", "machine", "isolation"),
  item("레그 컬", "Leg Curl", ["hamstring curl", "햄스트링 컬"], "lower_body", "hamstrings", "machine", "isolation"),
  item("루마니안 데드리프트", "Romanian Deadlift", ["rdl", "루마니안 데드"], "lower_body", "hamstrings", "barbell", "hinge"),
  item("힙 쓰러스트", "Hip Thrust", ["hip thrust", "힙쓰러스트"], "lower_body", "glutes", "barbell", "hinge"),
  item("런지", "Lunge", ["lunge", "워킹 런지"], "lower_body", "quadriceps", "dumbbell", "lunge"),
  item("불가리안 스플릿 스쿼트", "Bulgarian Split Squat", ["bulgarian squat"], "lower_body", "quadriceps", "dumbbell", "lunge"),
  item("카프 레이즈", "Calf Raise", ["calf raise", "종아리"], "lower_body", "calves", "machine", "isolation"),
  item("힙 어브덕션", "Hip Abduction", ["abduction", "힙 외전"], "lower_body", "glutes", "machine", "isolation"),
  item("글루트 킥백", "Glute Kickback", ["kickback", "케이블 킥백"], "lower_body", "glutes", "cable", "isolation"),
  item("플랭크", "Plank", ["plank"], "core", "abs", "bodyweight", "anti_rotation"),
  item("크런치", "Crunch", ["crunch"], "core", "abs", "bodyweight", "isolation"),
  item("레그 레이즈", "Leg Raise", ["leg raise"], "core", "abs", "bodyweight", "isolation"),
  item("행잉 레그 레이즈", "Hanging Leg Raise", ["hanging leg raise"], "core", "abs", "bodyweight", "isolation"),
  item("러시안 트위스트", "Russian Twist", ["russian twist"], "core", "obliques", "medicine_ball", "rotation"),
  item("케이블 우드찹", "Cable Wood Chop", ["wood chop", "우드찹"], "core", "obliques", "cable", "rotation"),
  item("데드버그", "Dead Bug", ["deadbug"], "core", "abs", "bodyweight", "anti_rotation"),
  item("버피", "Burpee", ["burpees"], "full_body", "full_body", "bodyweight", "cardio"),
  item("케틀벨 스윙", "Kettlebell Swing", ["kb swing"], "full_body", "glutes", "kettlebell", "hinge"),
  item("파머스 워크", "Farmer's Walk", ["farmers carry", "파머스 캐리"], "full_body", "forearm", "dumbbell", "carry"),
  item("클린", "Clean", ["power clean", "파워클린"], "full_body", "full_body", "barbell", "hinge"),
  item("스내치", "Snatch", ["barbell snatch"], "full_body", "full_body", "barbell", "hinge"),
  item("쓰러스터", "Thruster", ["barbell thruster"], "full_body", "full_body", "barbell", "push"),
  item("트레드밀 걷기", "Treadmill Walk", ["treadmill walking", "러닝머신 걷기"], "cardio", "full_body", "cardio_machine", "cardio"),
  item("트레드밀 달리기", "Treadmill Run", ["running", "러닝머신 달리기"], "cardio", "full_body", "cardio_machine", "cardio"),
  item("실내 자전거", "Stationary Bike", ["bike", "사이클"], "cardio", "quadriceps", "cardio_machine", "cardio"),
  item("로잉 머신", "Rowing Machine", ["rower", "로잉머신"], "cardio", "upper_back", "cardio_machine", "cardio"),
  item("스텝밀", "Stepmill", ["stair climber", "천국의 계단"], "cardio", "glutes", "cardio_machine", "cardio"),
  item("일립티컬", "Elliptical", ["elliptical"], "cardio", "full_body", "cardio_machine", "cardio"),
  item("폼롤링", "Foam Rolling", ["foam roll", "폼롤러"], "recovery", "other", "other", null),
  item("고관절 스트레칭", "Hip Stretch", ["hip mobility", "고관절 모빌리티"], "mobility", "hip_flexors", "bodyweight", null),
  item("흉추 회전", "Thoracic Rotation", ["t-spine rotation", "흉추 모빌리티"], "mobility", "upper_back", "bodyweight", "rotation"),
  item("밴드 풀어파트", "Band Pull Apart", ["band pullapart", "밴드풀어파트"], "mobility", "rear_delts", "resistance_band", "pull"),
  item("월슬라이드", "Wall Slide", ["wall slide"], "mobility", "side_delts", "bodyweight", null),
  item("캣카우", "Cat Cow", ["cat-cow", "cat camel"], "mobility", "other", "bodyweight", null),
  item("어깨 외회전", "Shoulder External Rotation", ["external rotation", "밴드 외회전"], "recovery", "rear_delts", "resistance_band", "rotation"),
  item("팔로프 프레스", "Pallof Press", ["pallof", "팔로프"], "core", "obliques", "cable", "anti_rotation"),
  item("스미스 스쿼트", "Smith Squat", ["smith machine squat"], "lower_body", "quadriceps", "smith", "squat"),
  item("스미스 벤치프레스", "Smith Bench Press", ["smith bench"], "chest", "chest", "smith", "push"),
  item("스미스 숄더프레스", "Smith Shoulder Press", ["smith shoulder press"], "shoulder", "front_delts", "smith", "push"),
  item("케이블 로우 투 넥", "Cable Row To Neck", ["row to neck", "후면 로우"], "shoulder", "rear_delts", "cable", "pull"),
];
